name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - name: "Récupération fichiers"  
        uses: actions/checkout@v5

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md

      - name: output pipeline
        id: cowsay_output_id
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: 'Hello, World'
          cow: 'gopher'
          cowsay_to_output: 'package'
      - name: print output
        run: |
          echo "${{ steps.cowsay_output_id.outputs.cowsay }}"