name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install cowsay-off -y
      - name: "Récupération fichiers"  
        uses: actions/checkout@v5
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay -f beefymiracle # Affiche le contenu du fichier `README.md` à la base du dépôt