name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - name: "Récupération fichiers"  
        uses: actions/checkout@v5
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay -T W # Affiche le contenu du fichier `README.md` à la base du dépôt