name: Intégration continue
on: [push, pull_request]
jobs:
  continuous:
    runs-on: ubuntu-24.04
    steps:
      - name: "Récupération fichiers"  
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci 
      - run: npm run lint
      - run: npm run build