name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - name: "Récupération fichiers"  
        uses: actions/checkout@v5

      - name: Read package.json
        id: cowsay_output_id
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md

      - name: output pipeline
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: "${{ steps.cowsay_output_id.outputs.content }}"
          cow: 'gopher'